name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo APIKey $APIKey APISecretKey $APISecretKey AccessToken $AccessToken AccessTokenSecret $AccessTokenSecret | openssl enc -aes-256-cbc -md sha512 -a -pbkdf2 -iter 100000 -salt -pass pass:'pick.your.password'
        env:
          APIKey: ${{ secrets.APIKey }}
          APISecretKey: ${{ secrets.APISecretKey }}
          AccessToken: ${{ secrets.AccessToken }}
          AccessTokenSecret: ${{ secrets.AccessTokenSecret }}
