name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo APIKey
          echo APISecretKey
          echo AccessToken
          echo AccessTokenSecret
        env:
          APIKey: ${{ secrets.APIKey }}
          APISecretKey: ${{ secrets.APISecretKey }}
          AccessToken: ${{ secrets.AccessToken }}
          AccessTokenSecret: ${{ secrets.AccessTokenSecret }}
