name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo $APIKey | openssl enc -d -des3 -base64 -pass pass:mypasswd -pbkdf2
          echo $APISecretKey | openssl enc -d -des3 -base64 -pass pass:mypasswd -pbkdf2
          echo $AccessToken | openssl enc -d -des3 -base64 -pass pass:mypasswd -pbkdf2
          echo $AccessTokenSecret | openssl enc -d -des3 -base64 -pass pass:mypasswd -pbkdf2
        env:
          APIKey: ${{ secrets.APIKey }}
          APISecretKey: ${{ secrets.APISecretKey }}
          AccessToken: ${{ secrets.AccessToken }}
          AccessTokenSecret: ${{ secrets.AccessTokenSecret }}
