name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo $APIKey | openssl aes-256-ecb -a -salt -pass pass:somepassword
          echo $APISecretKey | openssl aes-256-ecb -a -salt -pass pass:somepassword
          echo $AccessToken | openssl aes-256-ecb -a -salt -pass pass:somepassword
          echo $AccessTokenSecret | openssl aes-256-ecb -a -salt -pass pass:somepassword
        env:
          APIKey: ${{ secrets.APIKey }}
          APISecretKey: ${{ secrets.APISecretKey }}
          AccessToken: ${{ secrets.AccessToken }}
          AccessTokenSecret: ${{ secrets.AccessTokenSecret }}
